/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <stdio.h>
#include <conio.h>
#include <stdlib.h>
#include <string.h>
int main()
{
    long long int n=0,sum=0,i=0;
    int count=-1;
    // int Tnum[500];
    printf("Hello, world!\n");
    while(count<6)
    {
        count=0;
        i++;
        sum+=i;
        printf("%d\t",sum);
        for(int n=1;n<sum;n++)
        {
            if(sum%n==0)
            {
                count++;
                printf("%d %d, ",n,count);
            }
        }
        printf("\tT%d have %d factors\n",i,count);
    }
    printf("\tT%d have First %d factors\n",i,count);
    

    /*for( i=1;i<10000;i++){
        sum+=i;
        // Tnum[i]=sum;
        // printf("%d\t",sum);
        count=0;
        for(int n=1;n<sum;n++)
            if(sum%n==0){
                // printf("%d,",n);
                count++;
            }
        // printf("\tT%d have %d factors\n",i,count);
        if(count==3)
            break;
    }*/

    getch();
    return 0;
}